@startuml
left to right direction
actor Developer as Dev

rectangle Customer {
  actor "Customer Dev" as Customerdev
}

!include debian_packages/internal-devel-deb.plantuml
!include debian_packages/external-sdk-deb.plantuml


rectangle InternalDevelopment {
  usecase "Run tools with given version on PC" as UC1
  usecase "Read engineering documentation" as UC2
  usecase "Read software documentation" as UC3
}

rectangle ExternalDevelopment {
  usecase "Develop suplier tool" as UC_Ext1
  usecase "Read sdk documentation" as UC_Ext2
}

' UC1
Dev --> UC1
' UC2
Dev --> UC2
DevReqEngDoc -->UC2
' UC3
Dev -->UC3
DevBuildPipeDoc -->UC3
DevCodeDoxy -->UC3
DevProcessWeb -->UC3

' UC_Ext1
Customerdev --> UC_Ext1
SdkPubHeaders --> UC_Ext1
SdkDynLib --> UC_Ext1
' UC_Ext2
Customerdev --> UC_Ext2
SdkDoc --> UC_Ext2

@enduml
