// Copyright 2024 <Maxime Haselbauer>
#ifndef SOFTWARE_IN_THE_LOOP_SOFTWARE_IN_THE_LOOP_CONFIGURATION_H
#define SOFTWARE_IN_THE_LOOP_SOFTWARE_IN_THE_LOOP_CONFIGURATION_H
const char kFakeImuSilDeviceFilePath[] = "/tmp/vserial_sil_side";
#endif  // SOFTWARE_IN_THE_LOOP_SOFTWARE_IN_THE_LOOP_CONFIGURATION_H
