// Copyright 2024 <Maxime Haselbauer>
#ifndef FLIGHT_SOFTWARE_DEPLOYMENT_LINUX_FLIGHT_SOFTWARE_LINUX_CONFIGURATION_H
#define FLIGHT_SOFTWARE_DEPLOYMENT_LINUX_FLIGHT_SOFTWARE_LINUX_CONFIGURATION_H
const char kUartImuDeviceFilePath[] = "/tmp/vserial_flight_software_side";

#endif  // FLIGHT_SOFTWARE_DEPLOYMENT_LINUX_FLIGHT_SOFTWARE_LINUX_CONFIGURATION_H
