@startuml
package "internal-devel.deb" {
        folder "/usr/share/flight-software"  {
            [requirements_engineering.pdf] as DevReqEngDoc #Orange
            [build_pipeline_documentation.pdf] as DevBuildPipeDoc #Orange
            [Doxygen (flight-software)] as DevCodeDoxy #Orange
            [Processes description website] as DevProcessWeb #Orange
            [Doxygen (cFS)] as DevCFSIntegrationDoxy #Orange
        }
        folder "/usr/include/flight-software" {
            [Public headers] as DevPubHeaders #LightBlue
        }
        folder "/usr/lib/flight-software" {
            [Dynamic libraries (flight-software)] as DevDynLib #LightBlue
            [Dynamic Libraries (cFS)] as DevCFSDynLib #DarkCyan
        }
        folder "/usr/bin" {
            [Binaries (flight-software)] as DevBin #LightCyan
            [Tools (flight-software)]   as DevTools #LightCyan
            [Binaries (cFS)]    as DevCFSBin #DarkCyan
            [Tools (cFS)] as DevCFSTools #LightSkyBlue
        }
        folder "/etc/cFS" {
            [Configuration files (cFS)] as DevcFSConfFile #DarkCyan
        }
}

@enduml
